using System;

namespace MSF.Powershell.Meterpreter
{
    public enum PacketType : uint
    {
        Request = 0u,
        Response = 1u,
        PlainRequest = 10u,
        PlainResponse = 11u
    };

    [Flags]
    public enum MetaType : uint
    {
        None = 0u,
        String = 1u << 16,
        Uint = 1u << 17,
        Raw = 1u << 18,
        Bool = 1u << 19,
        Qword = 1u << 20,
        Compressed = 1u << 21,

        Group = 1u << 30,
        Complex = 1u << 31,

        All = (String | Uint | Raw | Bool | Qword | Compressed | Group | Complex)
    };

    public enum ExtensionBase : uint
    {
        Stdapi = 0u,
        Incognito = 20000u,
        Priv = 20000u,
        Kiwi = 20000u
    };

    public enum PacketMethod : uint
    {
        CoreChannelClose = 1000u,
        CoreChannelEof = 1001u,
        CoreChannelInteract = 1002u,
        CoreChannelOpen = 1003u,
        CoreChannelRead = 1004u,
        CoreChannelSeek = 1005u,
        CoreChannelTell = 1006u,
        CoreChannelWrite = 1007u,
        CoreConsoleWrite = 1008u,
        CoreEnumextcmd = 1009u,
        CoreGetSessionGuid = 1010u,
        CoreLoadlib = 1011u,
        CoreMachineId = 1012u,
        CoreMigrate = 1013u,
        CoreNativeArch = 1014u,
        CoreNegotiateTlvEncryption = 1015u,
        CorePatchUrl = 1016u,
        CorePivotAdd = 1017u,
        CorePivotRemove = 1018u,
        CorePivotSessionDied = 1019u,
        CorePivotSessionNew = 1020u,
        CoreSetSessionGuid = 1021u,
        CoreSetUuid = 1022u,
        CoreShutdown = 1023u,
        CoreTransportAdd = 1024u,
        CoreTransportChange = 1025u,
        CoreTransportGetcerthash = 1026u,
        CoreTransportList = 1027u,
        CoreTransportNext = 1028u,
        CoreTransportPrev = 1029u,
        CoreTransportRemove = 1030u,
        CoreTransportSetTimeouts = 1031u,
        CoreTransportSetcerthash = 1032u,
        CoreTransportSleep = 1033u,
        CoreMethodMax = CoreTransportSleep,
        StdapiAudioMicList = 2000u,
        StdapiAudioMicStart = 2001u,
        StdapiAudioMicStop = 2002u,
        StdapiFsChdir = 2003u,
        StdapiFsChmod = 2004u,
        StdapiFsDeleteDir = 2005u,
        StdapiFsDeleteFile = 2006u,
        StdapiFsFileCopy = 2007u,
        StdapiFsFileExpandPath = 2008u,
        StdapiFsFileMove = 2009u,
        StdapiFsGetwd = 2010u,
        StdapiFsLs = 2011u,
        StdapiFsMd5 = 2012u,
        StdapiFsMkdir = 2013u,
        StdapiFsMountShow = 2014u,
        StdapiFsSearch = 2015u,
        StdapiFsSeparator = 2016u,
        StdapiFsSha1 = 2017u,
        StdapiFsStat = 2018u,
        StdapiNetConfigAddRoute = 2019u,
        StdapiNetConfigGetArpTable = 2020u,
        StdapiNetConfigGetInterfaces = 2021u,
        StdapiNetConfigGetNetstat = 2022u,
        StdapiNetConfigGetProxy = 2023u,
        StdapiNetConfigGetRoutes = 2024u,
        StdapiNetConfigRemoveRoute = 2025u,
        StdapiNetResolveHost = 2026u,
        StdapiNetResolveHosts = 2027u,
        StdapiNetSocketTcpShutdown = 2028u,
        StdapiRailgunApi = 2029u,
        StdapiRailgunApiMulti = 2030u,
        StdapiRailgunMemread = 2031u,
        StdapiRailgunMemwrite = 2032u,
        StdapiRegistryCheckKeyExists = 2033u,
        StdapiRegistryCloseKey = 2034u,
        StdapiRegistryCreateKey = 2035u,
        StdapiRegistryDeleteKey = 2036u,
        StdapiRegistryDeleteValue = 2037u,
        StdapiRegistryEnumKey = 2038u,
        StdapiRegistryEnumKeyDirect = 2039u,
        StdapiRegistryEnumValue = 2040u,
        StdapiRegistryEnumValueDirect = 2041u,
        StdapiRegistryLoadKey = 2042u,
        StdapiRegistryOpenKey = 2043u,
        StdapiRegistryOpenRemoteKey = 2044u,
        StdapiRegistryQueryClass = 2045u,
        StdapiRegistryQueryValue = 2046u,
        StdapiRegistryQueryValueDirect = 2047u,
        StdapiRegistrySetValue = 2048u,
        StdapiRegistrySetValueDirect = 2049u,
        StdapiRegistryUnloadKey = 2050u,
        StdapiSysConfigDriverList = 2051u,
        StdapiSysConfigDropToken = 2052u,
        StdapiSysConfigGetenv = 2053u,
        StdapiSysConfigGetprivs = 2054u,
        StdapiSysConfigGetsid = 2055u,
        StdapiSysConfigGetuid = 2056u,
        StdapiSysConfigLocaltime = 2057u,
        StdapiSysConfigRev2self = 2058u,
        StdapiSysConfigStealToken = 2059u,
        StdapiSysConfigSysinfo = 2060u,
        StdapiSysEventlogClear = 2061u,
        StdapiSysEventlogClose = 2062u,
        StdapiSysEventlogNumrecords = 2063u,
        StdapiSysEventlogOldest = 2064u,
        StdapiSysEventlogOpen = 2065u,
        StdapiSysEventlogRead = 2066u,
        StdapiSysPowerExitwindows = 2067u,
        StdapiSysProcessAttach = 2068u,
        StdapiSysProcessClose = 2069u,
        StdapiSysProcessExecute = 2070u,
        StdapiSysProcessGetInfo = 2071u,
        StdapiSysProcessGetProcesses = 2072u,
        StdapiSysProcessGetpid = 2073u,
        StdapiSysProcessImageGetImages = 2074u,
        StdapiSysProcessImageGetProcAddress = 2075u,
        StdapiSysProcessImageLoad = 2076u,
        StdapiSysProcessImageUnload = 2077u,
        StdapiSysProcessKill = 2078u,
        StdapiSysProcessMemoryAllocate = 2079u,
        StdapiSysProcessMemoryFree = 2080u,
        StdapiSysProcessMemoryLock = 2081u,
        StdapiSysProcessMemoryProtect = 2082u,
        StdapiSysProcessMemoryQuery = 2083u,
        StdapiSysProcessMemoryRead = 2084u,
        StdapiSysProcessMemoryUnlock = 2085u,
        StdapiSysProcessMemoryWrite = 2086u,
        StdapiSysProcessThreadClose = 2087u,
        StdapiSysProcessThreadCreate = 2088u,
        StdapiSysProcessThreadGetThreads = 2089u,
        StdapiSysProcessThreadOpen = 2090u,
        StdapiSysProcessThreadQueryRegs = 2091u,
        StdapiSysProcessThreadResume = 2092u,
        StdapiSysProcessThreadSetRegs = 2093u,
        StdapiSysProcessThreadSuspend = 2094u,
        StdapiSysProcessThreadTerminate = 2095u,
        StdapiSysProcessWait = 2096u,
        StdapiTcpChannelOpen = 2097u,
        StdapiUiDesktopEnum = 2098u,
        StdapiUiDesktopGet = 2099u,
        StdapiUiDesktopScreenshot = 2100u,
        StdapiUiDesktopSet = 2101u,
        StdapiUiEnableKeyboard = 2102u,
        StdapiUiEnableMouse = 2103u,
        StdapiUiGetIdleTime = 2104u,
        StdapiUiGetKeys = 2105u,
        StdapiUiGetKeysUtf8 = 2106u,
        StdapiUiSendKeys = 2107u,
        StdapiUiSendMouse = 2108u,
        StdapiUiStartKeyscan = 2109u,
        StdapiUiStopKeyscan = 2110u,
        StdapiUiUnlockDesktop = 2111u,
        StdapiWebcamAudioRecord = 2112u,
        StdapiWebcamGetFrame = 2113u,
        StdapiWebcamList = 2114u,
        StdapiWebcamStart = 2115u,
        StdapiWebcamStop = 2116u,
        PrivElevateGetsystem = 3000u,
        PrivFsBlankDirectoryMace = 3001u,
        PrivFsBlankFileMace = 3002u,
        PrivFsGetFileMace = 3003u,
        PrivFsSetFileMace = 3004u,
        PrivFsSetFileMaceFromFile = 3005u,
        PrivPasswdGetSamHashes = 3006u,
        ExtapiAdsiDomainQuery = 4000u,
        ExtapiClipboardGetData = 4001u,
        ExtapiClipboardMonitorDump = 4002u,
        ExtapiClipboardMonitorPause = 4003u,
        ExtapiClipboardMonitorPurge = 4004u,
        ExtapiClipboardMonitorResume = 4005u,
        ExtapiClipboardMonitorStart = 4006u,
        ExtapiClipboardMonitorStop = 4007u,
        ExtapiClipboardSetData = 4008u,
        ExtapiNtdsParse = 4009u,
        ExtapiPageantSendQuery = 4010u,
        ExtapiServiceControl = 4011u,
        ExtapiServiceEnum = 4012u,
        ExtapiServiceQuery = 4013u,
        ExtapiWindowEnum = 4014u,
        ExtapiWmiQuery = 4015u,
        IncognitoAddGroupUser = 5000u,
        IncognitoAddLocalgroupUser = 5001u,
        IncognitoAddUser = 5002u,
        IncognitoImpersonateToken = 5003u,
        IncognitoListTokens = 5004u,
        IncognitoSnarfHashes = 5005u,
        KiwiExecCmd = 6000u,
        AndroidActivityStart = 7000u,
        AndroidCheckRoot = 7001u,
        AndroidDeviceShutdown = 7002u,
        AndroidDumpCalllog = 7003u,
        AndroidDumpContacts = 7004u,
        AndroidDumpSms = 7005u,
        AndroidGeolocate = 7006u,
        AndroidHideAppIcon = 7007u,
        AndroidIntervalCollect = 7008u,
        AndroidSendSms = 7009u,
        AndroidSetAudioMode = 7010u,
        AndroidSetWallpaper = 7011u,
        AndroidSqliteQuery = 7012u,
        AndroidWakelock = 7013u,
        AndroidWlanGeolocate = 7014u,
        AppapiAppInstall = 8000u,
        AppapiAppList = 8001u,
        AppapiAppRun = 8002u,
        AppapiAppUninstall = 8003u,
        DumpRam = 9000u,
        EspiaAudioGetDevAudio = 10000u,
        EspiaImageGetDevScreen = 10001u,
        EspiaVideoGetDevImage = 10002u,
        LanattacksAddTftpFile = 11000u,
        LanattacksDhcpLog = 11001u,
        LanattacksResetDhcp = 11002u,
        LanattacksResetTftp = 11003u,
        LanattacksSetDhcpOption = 11004u,
        LanattacksStartDhcp = 11005u,
        LanattacksStartTftp = 11006u,
        LanattacksStopDhcp = 11007u,
        LanattacksStopTftp = 11008u,
        MimikatzCustomCommand = 12000u,
        NetworkpugStart = 13000u,
        NetworkpugStop = 13001u,
        PeinjectorInjectShellcode = 14000u,
        PowershellAssemblyLoad = 15000u,
        PowershellExecute = 15001u,
        PowershellSessionRemove = 15002u,
        PowershellShell = 15003u,
        PythonExecute = 16000u,
        PythonReset = 16001u,
        SnifferCaptureDump = 17000u,
        SnifferCaptureDumpRead = 17001u,
        SnifferCaptureRelease = 17002u,
        SnifferCaptureStart = 17003u,
        SnifferCaptureStats = 17004u,
        SnifferCaptureStop = 17005u,
        SnifferInterfaces = 17006u,
        UnhookPe = 18000u,
    };

    public enum TlvType : uint
    {
        // Actual types
        Any = MetaType.None,
        Method = MetaType.String | 1u,
        RequestId = MetaType.String | 2u,
        Exception = MetaType.Group | 3u,
        Result = MetaType.Uint | 4u,
        MethodId = MetaType.Uint | 5u,

        String = MetaType.String | 10u,
        Uint = MetaType.Uint | 11u,
        Bool = MetaType.Bool | 12u,

        Length = MetaType.Uint | 25u,
        Data = MetaType.Raw | 26u,
        Flags = MetaType.Uint | 27u,

        ChannelId = MetaType.Uint | 50u,
        ChannelType = MetaType.String | 51u,
        ChannelData = MetaType.Raw | 52u,
        ChannelDataGroup = MetaType.Group | 53u,
        ChannelClass = MetaType.Uint | 54u,
        ChannelParentId = MetaType.Uint | 55u,

        SeekWhence = MetaType.Uint | 70u,
        SeekOffset = MetaType.Uint | 71u,
        SeekPos = MetaType.Uint | 72u,

        ExceptionCode = MetaType.Uint | 300u,
        ExceptionString = MetaType.String | 301u,

        LibraryPath = MetaType.String | 400u,
        TargetPath = MetaType.String | 401u,
        MigratePid = MetaType.Uint | 402u,
        MigrateLen = MetaType.Uint | 403u,

        TransType = MetaType.Uint | 430u,
        TransUrl = MetaType.String | 431u,
        TransUa = MetaType.String | 432u,
        TransCommTimeout = MetaType.Uint | 433u,
        TransSessExp = MetaType.Uint | 434u,
        TransCertHash = MetaType.Raw | 435u,
        TransProxyHost = MetaType.String | 436u,
        TransProxyUser = MetaType.String | 437u,
        TransProxyPass = MetaType.String | 438u,
        TransRetryTotal = MetaType.Uint | 439u,
        TransRetryWait = MetaType.Uint | 440u,
        TransHeaders = MetaType.String | 441u,
        TransGroup = MetaType.Group | 442u,

        MachineId = MetaType.String | 460u,
        Uuid = MetaType.Raw | 461u,

        CipherName = MetaType.String | 500u,
        CipherParameters = MetaType.Group | 501u,

        PeerHost = MetaType.String | 1500u,
        PeerPort = MetaType.Uint | 1501u,
        LocalHost = MetaType.String | 1502u,
        LocalPort = MetaType.Uint | 1503u,

        // STDAPI stuff
        ComputerName = MetaType.String | (ExtensionBase.Stdapi + 1040u),
        OsName = MetaType.String | (ExtensionBase.Stdapi + 1041u),
        UserName = MetaType.String | (ExtensionBase.Stdapi + 1042u),
        Architecture = MetaType.String | (ExtensionBase.Stdapi + 1043u),
        LangSystem = MetaType.String | (ExtensionBase.Stdapi + 1044u),
        Sid = MetaType.String | (ExtensionBase.Stdapi + 1045u),
        Domain = MetaType.String | (ExtensionBase.Stdapi + 1046u),
        LoggedOnUserCount = MetaType.Uint | (ExtensionBase.Stdapi + 1047u),

        Mount = MetaType.Group | (ExtensionBase.Stdapi + 1207u),
        MountName = MetaType.String | (ExtensionBase.Stdapi + 1208u),
        MountType = MetaType.Uint | (ExtensionBase.Stdapi + 1209u),
        MountSpaceUser = MetaType.Qword | (ExtensionBase.Stdapi + 1210u),
        MountSpaceTotal = MetaType.Qword | (ExtensionBase.Stdapi + 1211u),
        MountSpaceFree = MetaType.Qword | (ExtensionBase.Stdapi + 1212u),
        MountUncPath = MetaType.String | (ExtensionBase.Stdapi + 1213u),

        Pid = MetaType.Uint | (ExtensionBase.Stdapi + 2300u),
        ProcessName = MetaType.String | (ExtensionBase.Stdapi + 2301u),
        ProcessPath = MetaType.String | (ExtensionBase.Stdapi + 2302u),
        ProcessGroup = MetaType.Group | (ExtensionBase.Stdapi + 2303u),
        ProcessArch = MetaType.Uint | (ExtensionBase.Stdapi + 2306u),
        ParentPid = MetaType.Uint | (ExtensionBase.Stdapi + 2307u),
        ProcessSession = MetaType.Uint | (ExtensionBase.Stdapi + 2308u),

        // PRIV stuff
        ElevateTechnique = MetaType.Uint | (ExtensionBase.Priv + 200u),
        ElevateServiceName = MetaType.String | (ExtensionBase.Priv + 201u),

        // KIWI stuff
        KiwiCmd = MetaType.String | (ExtensionBase.Kiwi + 100u),
        KiwiCmdResult = MetaType.String | (ExtensionBase.Kiwi + 101u),

        // INCOGNITO stuff
        IncognitoListTokensDelegation = MetaType.String | (ExtensionBase.Incognito + 2u),
        IncognitoListTokensImpersonation = MetaType.String | (ExtensionBase.Incognito + 3u),
        IncognitoListTokensTokenOrder = MetaType.Uint | (ExtensionBase.Incognito + 4u),
        IncognitoImpersonateToken = MetaType.String | (ExtensionBase.Incognito + 5u),
        IncognitoGenericResponse = MetaType.String | (ExtensionBase.Incognito + 6u),
        IncognitoUserName = MetaType.String | (ExtensionBase.Incognito + 7u),
        IncognitoPassword = MetaType.String | (ExtensionBase.Incognito + 8u),
        IncognitoServerName = MetaType.String | (ExtensionBase.Incognito + 9u),
        IncognitoGroupName = MetaType.String | (ExtensionBase.Incognito + 10u)
    };
}
